# Generated by Django 2.2.10 on 2020-06-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20)),
                ('task_desc', models.CharField(max_length=200)),
                ('task_ima', models.ImageField(default='', upload_to='assistant/images')),
            ],
        ),
    ]
