# Generated by Django 2.2.10 on 2020-06-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_auto_20200627_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_url',
            field=models.CharField(default='#', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_ima',
            field=models.ImageField(default='../default.png', upload_to='assistant/images/'),
        ),
    ]
