# Generated by Django 2.2.10 on 2020-06-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_auto_20200628_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_ima',
            field=models.ImageField(default='assistant/images/default.png', upload_to='assistant/images/'),
        ),
    ]
