# Generated by Django 2.2.10 on 2020-06-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_auto_20200628_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_ima',
            field=models.ImageField(upload_to='assistant/images/'),
        ),
    ]
