# Generated by Django 2.2.10 on 2020-06-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_auto_20200628_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('Description', models.CharField(max_length=300)),
            ],
        ),
    ]
