# Generated by Django 2.2.10 on 2020-06-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_item', models.CharField(max_length=80)),
                ('expense_cost', models.FloatField()),
                ('date_added', models.DateTimeField()),
            ],
        ),
    ]
