# Generated by Django 2.2.10 on 2020-06-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0008_expenseinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseinfo',
            name='expense_cat',
            field=models.CharField(default='Others', max_length=10),
        ),
    ]
