# Generated by Django 2.2.10 on 2020-06-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0009_expenseinfo_expense_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseinfo',
            name='expense_piechart',
            field=models.ImageField(default='assistant/images/expense.jpg', upload_to='assistant/images'),
        ),
    ]
