# Generated by Django 2.2.10 on 2020-06-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0010_expenseinfo_expense_piechart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseinfo',
            name='expense_piechart',
        ),
        migrations.AlterField(
            model_name='expenseinfo',
            name='date_added',
            field=models.DateField(),
        ),
    ]
