# Generated by Django 2.2.10 on 2020-07-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0013_auto_20200630_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goals_desc', models.CharField(max_length=40)),
                ('Goals_prog', models.IntegerField(default=0)),
            ],
        ),
    ]
