# Generated by Django 2.2.10 on 2020-07-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0014_goals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passstore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('account_pass', models.CharField(max_length=128, verbose_name='password')),
            ],
        ),
    ]
