# Generated by Django 2.2.10 on 2020-07-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0015_passstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bday_name', models.CharField(max_length=20)),
                ('bday_date', models.DateField()),
            ],
        ),
    ]
