# Generated by Django 2.2.10 on 2020-07-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0016_bday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bday',
            name='bday_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='passstore',
            name='account_pass',
            field=models.CharField(max_length=20),
        ),
    ]
