# Generated by Django 2.2.10 on 2020-07-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0017_auto_20200702_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bday',
            name='bday_date',
            field=models.DateField(),
        ),
    ]
