# Generated by Django 2.2.10 on 2020-07-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0022_auto_20200705_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bday',
            name='bday_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='passstore',
            name='account_pass',
            field=models.BinaryField(),
        ),
    ]
