# Generated by Django 2.2.10 on 2020-07-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0025_auto_20200705_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
